#!/bin/bash

###############################################################
#          jupyter/jupyterlab extensions/kernels              #
###############################################################

# Beakerx installation 
# echo "Beakerx install"
# beakerx install
# echo "Beakerx extensions install"
# jupyter labextension install beakerx-jupyterlab --no-build 

# echo "IPywidgets Jupyterlab"
# jupyter labextension install @jupyter-widgets/jupyterlab-manager


# # Table of contents Jupyter Lab Extension
# echo "Table of contents Jupyter Lab extension install"
# jupyter labextension install @jupyterlab/toc --no-build 

# Jupyter/Jupyterlab extension for proxying internal applications
# echo "Jupyter/Jupyterlab proxy extension install"
# jupyter serverextension enable --py jupyter_server_proxy
# jupyter labextension install jupyterlab-server-proxy


# Building everything up
echo "Building everything up (jupyter lab build)"
# jupyter lab build 



###############################################################
#             zsh and ohmyzsh installation                    #
###############################################################

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
sed -i 's/^ZSH_THEME=.*/ZSH_THEME="gnzh"/' ~/.zshrc
chsh -s $(which zsh)

###############################################################
#             moving to a local installation folder           #
###############################################################

mkdir ~/resources/local
cd    ~/resources/local

###############################################################
#             influxdb installation                           #
###############################################################

export INFLUXDB_VERSION=3.9.2
echo "export INFLUXDB_VERSION=${INFLUXDB_VERSION}" >> ~/.bashrc
echo "export INFLUXDB_VERSION=${INFLUXDB_VERSION}" >> ~/.profile

export INFLUXDB_HOME=$(pwd)/influxdb3-core-${INFLUXDB_VERSION}
echo "export INFLUXDB_HOME=${INFLUXDB_HOME}"       >> ~/.bashrc
echo "export INFLUXDB_HOME=${INFLUXDB_HOME}"       >> ~/.profile

# Download and install influxdb3 server
wget https://dl.influxdata.com/influxdb/releases/influxdb3-core-${INFLUXDB_VERSION}_linux_amd64.tar.gz -q
tar -zxf influxdb3-core-${INFLUXDB_VERSION}_linux_amd64.tar.gz >> /dev/null
rm       influxdb3-core-${INFLUXDB_VERSION}_linux_amd64.tar.gz
# adding bin/ to $path
echo "export PATH=\$PATH:\$INFLUXDB_HOME"   >> ~/.bashrc
echo "export PATH=\$PATH:\$INFLUXDB_HOME"   >> ~/.profile

###############################################################
#             influxdb CLI installation                       #
###############################################################

export INFLUXDBCLI_VERSION=2.12.0
echo "export INFLUXDBCLI_VERSION=${INFLUXDBCLI_VERSION}" >> ~/.bashrc
echo "export INFLUXDBCLI_VERSION=${INFLUXDBCLI_VERSION}" >> ~/.profile

mkdir $(pwd)/influxdb-cli-${INFLUXDBCLI_VERSION}
export INFLUXDBCLI_HOME=$(pwd)/influxdb-cli-${INFLUXDBCLI_VERSION}
echo "export INFLUXDBCLI_HOME=${INFLUXDBCLI_HOME}"       >> ~/.bashrc
echo "export INFLUXDBCLI_HOME=${INFLUXDBCLI_HOME}"       >> ~/.profile

# Download and install influxdb3 server
wget https://dl.influxdata.com/influxctl/releases/influxctl-v${INFLUXDBCLI_VERSION}-linux-x86_64.tar.gz -q
tar -zxf influxctl-v${INFLUXDBCLI_VERSION}-linux-x86_64.tar.gz >> /dev/null
rm       influxctl-v${INFLUXDBCLI_VERSION}-linux-x86_64.tar.gz
mv influxctl $(pwd)/influxdb-cli-${INFLUXDBCLI_VERSION}

# adding bin/ to $path
echo "export PATH=\$PATH:\$INFLUXDBCLI_HOME"   >> ~/.bashrc
echo "export PATH=\$PATH:\$INFLUXDBCLI_HOME"   >> ~/.profile


# https://dl.influxdata.com/influxdb/releases/influxdb3-core-3.9.2_linux_amd64.tar.gz
# https://dl.influxdata.com/influxctl/releases/influxctl-v2.12.0-linux-arm64.tar.gz
###############################################################
#             telegraf installation                           #
###############################################################


export TELEGRAF_VERSION=1.11.2
echo "export TELEGRAF_VERSION=${TELEGRAF_VERSION}" >> ~/.bashrc
echo "export TELEGRAF_VERSION=${TELEGRAF_VERSION}" >> ~/.profile

export TELEGRAF_HOME=$(pwd)/telegraf-${TELEGRAF_VERSION}
echo "export TELEGRAF_HOME=${TELEGRAF_HOME}"       >> ~/.bashrc
echo "export TELEGRAF_HOME=${TELEGRAF_HOME}"       >> ~/.profile



# Download and install telegraf
wget https://dl.influxdata.com/telegraf/releases/telegraf-${TELEGRAF_VERSION}_linux_amd64.tar.gz  -q
tar -zxf telegraf-${TELEGRAF_VERSION}_linux_amd64.tar.gz >> /dev/null
mv telegraf telegraf-$TELEGRAF_VERSION
rm       telegraf-${TELEGRAF_VERSION}_linux_amd64.tar.gz
# adding bin/ to $path
echo "export PATH=\$PATH:\$TELEGRAF_HOME/usr/bin"   >> ~/.bashrc
echo "export PATH=\$PATH:\$TELEGRAF_HOME/usr/bin"   >> ~/.profile


###############################################################
#             MongoDB installation commands                   #
###############################################################

echo "Installing MongoDB..."

export MONGODB_VERSION=8.3.1
echo "export MONGODB_VERSION=${MONGODB_VERSION}" >> ~/.bashrc
echo "export MONGODB_VERSION=${MONGODB_VERSION}" >> ~/.profile

export MONGODB_HOME=$(pwd)/mongodb-${MONGODB_VERSION}
echo "export MONGODB_HOME=${MONGODB_HOME}"       >> ~/.bashrc
echo "export MONGODB_HOME=${MONGODB_HOME}"       >> ~/.profile

wget  https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2204-${MONGODB_VERSION}.tgz -q && \
tar -xvf mongodb-linux-x86_64-ubuntu2204-${MONGODB_VERSION}.tgz >/dev/null                       && \
rm       mongodb-linux-x86_64-ubuntu2204-${MONGODB_VERSION}.tgz                                  && \
mv       mongodb-linux-x86_64-ubuntu2204-${MONGODB_VERSION}        mongodb-${MONGODB_VERSION}      

# adding bin and sbin to $path
echo "export PATH=\$PATH:\$MONGODB_HOME/bin"  >> ~/.bashrc
echo "export PATH=\$PATH:\$MONGODB_HOME/bin"  >> ~/.profile

echo "Finished installing MongoDB!"




###############################################################
#             grafana installation                           #
###############################################################


export GRAFANA_VERSION=6.2.5
echo "export GRAFANA_VERSION=${GRAFANA_VERSION}" >> ~/.bashrc
echo "export GRAFANA_VERSION=${GRAFANA_VERSION}" >> ~/.profile

export GRAFANA_HOME=$(pwd)/grafana-${GRAFANA_VERSION}
echo "export GRAFANA_HOME=${GRAFANA_HOME}"       >> ~/.bashrc
echo "export GRAFANA_HOME=${GRAFANA_HOME}"       >> ~/.profile



# Download and install telegraf
wget https://dl.grafana.com/oss/release/grafana-${GRAFANA_VERSION}.linux-amd64.tar.gz -q 
tar -zxvf grafana-${GRAFANA_VERSION}.linux-amd64.tar.gz >> /dev/null
rm        grafana-${GRAFANA_VERSION}.linux-amd64.tar.gz
# adding bin/ to $path
echo "export PATH=\$PATH:\$GRAFANA_HOME/bin"   >> ~/.bashrc
echo "export PATH=\$PATH:\$GRAFANA_HOME/bin"   >> ~/.profile



###############################################################
#             vscode installation                             #
###############################################################


export CODE_SERVER_VERSION=3.4.1
echo "export CODE_SERVER_VERSION=${CODE_SERVER_VERSION}" >> ~/.bashrc
echo "export CODE_SERVER_VERSION=${CODE_SERVER_VERSION}" >> ~/.profile

export CODE_SERVER_HOME=$(pwd)/code-server-${CODE_SERVER_VERSION}
echo "export CODE_SERVER_HOME=${CODE_SERVER_HOME}"       >> ~/.bashrc
echo "export CODE_SERVER_HOME=${CODE_SERVER_HOME}"       >> ~/.profile


# Download and install VS Code server
wget -q -O code-server.tar.gz https://github.com/cdr/code-server/releases/download/$CODE_SERVER_VERSION/code-server-$CODE_SERVER_VERSION-linux-x86_64.tar.gz                            
tar xzf code-server.tar.gz
mv code-server-${CODE_SERVER_VERSION}-linux-x86_64 code-server-$CODE_SERVER_VERSION
rm -rf code-server.tar.gz

# adding bin/ to $path
echo "export PATH=\$PATH:\$CODE_SERVER_HOME/bin"   >> ~/.bashrc
echo "export PATH=\$PATH:\$CODE_SERVER_HOME/bin"   >> ~/.profile

