#!/bin/bash

mkdir logs

chmod +x ~/binder/start.influxdb
chmod +x ~/binder/start.grafana
chmod +x ~/binder/start.telegraf
chmod +x ~/binder/start.mongodb 

printenv > logs/printenv.start

~/binder/start.influxdb  	&& \
~/binder/start.telegraf  	&& \
~/binder/start.mongodb  	&& \
~/binder/start.grafana  	&	

mosquitto   &	

export SHELL=/usr/bin/zsh

code-server .  --auth none &


# DO NOT REMOVE(!) 
# Here is why: https://mybinder.readthedocs.io/en/latest/config_files.html#start-run-code-before-the-user-sessions-starts
exec "$@"
